name: translation-ci 
on:
  push:
    branches:
      - main
      - prueba-languages
permissions:
  contents: write


jobs:
  deepl:
    name: DeepL
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: fabasoad/translation-action@v4
        id: deepl-step
        with:
          provider: deepl
          lang: es-pt-BR
          source: ../../docs/es/index.md 
          api_key: ${{secrets.DEEPL_API_KEY }}
      - name: Print the result
        run: echo "Translation is '${{ steps.deepl-step.outputs.text }}'"
        shell: sh
