name: translation-ci 
on:
  push:
    branches:
      - main
      - prueba-languages
permissions:
  contents: write


jobs:
  translate:
    name: translate
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: 3.x

      - run: pip install deepl markdown

      - name: Run translation
        env:
          DEEPL_API_KEY: ${{ secrets.DEEPL_API_KEY }}
        run: python translation-action/translate.py

